//! Typed budget domain: scopes, resource vectors, envelopes, pricing
//! snapshots, reservation state machine and operation receipts.
//!
//! All counters are checked unsigned integers. Money is expressed in integer
//! micro units (1 currency unit = 1_000_000 micros) of a local currency
//! declared by the experiment profile; no exchange-rate conversion happens
//! in this domain. Values are rejected before they can exceed the SQLite
//! signed `INTEGER` range.

use crate::budget::errors::AdmissionError;
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;

/// Maximum value storable in a SQLite signed `INTEGER` column. Ledger
/// counters must be converted through [`ensure_sqlite_range`] before being
/// written.
pub const SQLITE_INTEGER_MAX: u64 = i64::MAX as u64;

/// Rejects a counter value that cannot be stored in a SQLite `INTEGER`
/// column. Fail closed on overflow instead of wrapping or truncating.
pub fn ensure_sqlite_range(value: u64) -> Result<i64, AdmissionError> {
    if value > SQLITE_INTEGER_MAX {
        Err(AdmissionError::budget_exceeded(format!(
            "counter value {value} exceeds the SQLite INTEGER range"
        )))
    } else {
        Ok(value as i64)
    }
}

/// Converts a signed usage value reported by an owner into a checked
/// unsigned counter. Negative usage is a caller bug and fails closed.
pub fn checked_usage_u64(value: i64, dimension: ResourceDimension) -> Result<u64, AdmissionError> {
    if value < 0 {
        Err(AdmissionError::invalid_transition(format!(
            "negative usage for dimension {dimension:?}: {value}"
        )))
    } else {
        Ok(value as u64)
    }
}

/// The four budget scope levels, ordered from innermost to outermost.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ScopeKind {
    Request,
    Trial,
    Candidate,
    Campaign,
}

impl ScopeKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            ScopeKind::Request => "request",
            ScopeKind::Trial => "trial",
            ScopeKind::Candidate => "candidate",
            ScopeKind::Campaign => "campaign",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "request" => Some(ScopeKind::Request),
            "trial" => Some(ScopeKind::Trial),
            "candidate" => Some(ScopeKind::Candidate),
            "campaign" => Some(ScopeKind::Campaign),
            _ => None,
        }
    }

    /// The next outer scope kind, if any.
    pub fn parent(&self) -> Option<ScopeKind> {
        match self {
            ScopeKind::Request => Some(ScopeKind::Trial),
            ScopeKind::Trial => Some(ScopeKind::Candidate),
            ScopeKind::Candidate => Some(ScopeKind::Campaign),
            ScopeKind::Campaign => None,
        }
    }
}

/// A legal four-level scope chain. All identifiers are opaque strings
/// generated by the backend; external callers can never mint ownership by
/// supplying their own values through untrusted headers.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ScopeChain {
    pub request_id: String,
    pub trial_id: String,
    pub candidate_id: String,
    pub campaign_id: String,
}

impl ScopeChain {
    /// Validates that every level carries a non-empty, distinct opaque ID.
    /// Parent/child existence is verified durably by the ledger store.
    pub fn validate(&self) -> Result<(), AdmissionError> {
        let levels = [
            (ScopeKind::Request, &self.request_id),
            (ScopeKind::Trial, &self.trial_id),
            (ScopeKind::Candidate, &self.candidate_id),
            (ScopeKind::Campaign, &self.campaign_id),
        ];
        for (kind, id) in &levels {
            if id.trim().is_empty() {
                return Err(AdmissionError::invalid_scope_chain(format!(
                    "empty scope id for level {}",
                    kind.as_str()
                )));
            }
        }
        let ids: BTreeSet<&str> = levels.iter().map(|(_, id)| id.as_str()).collect();
        if ids.len() != levels.len() {
            return Err(AdmissionError::invalid_scope_chain(
                "scope chain contains duplicate scope ids across levels",
            ));
        }
        Ok(())
    }
}

/// Validates a scope chain and returns it back, failing closed on malformed
/// input. Convenience wrapper used by admission callers.
pub fn validate_scope_chain(chain: &ScopeChain) -> Result<(), AdmissionError> {
    chain.validate()
}

/// Every budgetable resource dimension, including the monetary dimension.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceDimension {
    InputTokens,
    OutputTokens,
    CacheReadTokens,
    CacheWriteTokens,
    WallTimeMs,
    ToolCalls,
    Processes,
    DiskBytes,
    NetworkBytes,
    Concurrency,
    Money,
}

impl ResourceDimension {
    /// All dimensions in canonical order.
    pub const ALL: [ResourceDimension; 11] = [
        ResourceDimension::InputTokens,
        ResourceDimension::OutputTokens,
        ResourceDimension::CacheReadTokens,
        ResourceDimension::CacheWriteTokens,
        ResourceDimension::WallTimeMs,
        ResourceDimension::ToolCalls,
        ResourceDimension::Processes,
        ResourceDimension::DiskBytes,
        ResourceDimension::NetworkBytes,
        ResourceDimension::Concurrency,
        ResourceDimension::Money,
    ];

    pub fn as_str(&self) -> &'static str {
        match self {
            ResourceDimension::InputTokens => "input_tokens",
            ResourceDimension::OutputTokens => "output_tokens",
            ResourceDimension::CacheReadTokens => "cache_read_tokens",
            ResourceDimension::CacheWriteTokens => "cache_write_tokens",
            ResourceDimension::WallTimeMs => "wall_time_ms",
            ResourceDimension::ToolCalls => "tool_calls",
            ResourceDimension::Processes => "processes",
            ResourceDimension::DiskBytes => "disk_bytes",
            ResourceDimension::NetworkBytes => "network_bytes",
            ResourceDimension::Concurrency => "concurrency",
            ResourceDimension::Money => "money_micros",
        }
    }
}

/// A per-dimension cap. Omission is never "unlimited": a dimension is either
/// an explicit hard cap or explicitly not applicable to this profile.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CapLimit {
    /// The dimension does not apply to this profile (e.g. disk bytes for a
    /// pure LLM call). It must not be silently treated as zero usage.
    NotApplicable,
    /// A hard cap. `committed + reserved + requested <= cap` is enforced.
    HardCap(u64),
}

impl CapLimit {
    pub fn limit(&self) -> Option<u64> {
        match self {
            CapLimit::NotApplicable => None,
            CapLimit::HardCap(value) => Some(*value),
        }
    }
}

/// Checked-integer resource vector. Every field is a non-negative counter;
/// money is in micro units of the profile currency.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct BudgetVector {
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read_tokens: u64,
    pub cache_write_tokens: u64,
    pub wall_time_ms: u64,
    pub tool_calls: u64,
    pub processes: u64,
    pub disk_bytes: u64,
    pub network_bytes: u64,
    /// Live concurrency lease count. Unlike additive dimensions this is
    /// occupied on reserve and released on commit/release/unknown.
    pub concurrency: u64,
    pub money_micros: u64,
}

impl BudgetVector {
    pub const ZERO: BudgetVector = BudgetVector {
        input_tokens: 0,
        output_tokens: 0,
        cache_read_tokens: 0,
        cache_write_tokens: 0,
        wall_time_ms: 0,
        tool_calls: 0,
        processes: 0,
        disk_bytes: 0,
        network_bytes: 0,
        concurrency: 0,
        money_micros: 0,
    };

    pub fn dimension(&self, dimension: ResourceDimension) -> u64 {
        match dimension {
            ResourceDimension::InputTokens => self.input_tokens,
            ResourceDimension::OutputTokens => self.output_tokens,
            ResourceDimension::CacheReadTokens => self.cache_read_tokens,
            ResourceDimension::CacheWriteTokens => self.cache_write_tokens,
            ResourceDimension::WallTimeMs => self.wall_time_ms,
            ResourceDimension::ToolCalls => self.tool_calls,
            ResourceDimension::Processes => self.processes,
            ResourceDimension::DiskBytes => self.disk_bytes,
            ResourceDimension::NetworkBytes => self.network_bytes,
            ResourceDimension::Concurrency => self.concurrency,
            ResourceDimension::Money => self.money_micros,
        }
    }

    /// Returns a copy with the given dimension set. Fails closed if the
    /// value exceeds the SQLite integer range.
    pub fn with_dimension(
        &self,
        dimension: ResourceDimension,
        value: u64,
    ) -> Result<BudgetVector, AdmissionError> {
        ensure_sqlite_range(value)?;
        let mut next = *self;
        match dimension {
            ResourceDimension::InputTokens => next.input_tokens = value,
            ResourceDimension::OutputTokens => next.output_tokens = value,
            ResourceDimension::CacheReadTokens => next.cache_read_tokens = value,
            ResourceDimension::CacheWriteTokens => next.cache_write_tokens = value,
            ResourceDimension::WallTimeMs => next.wall_time_ms = value,
            ResourceDimension::ToolCalls => next.tool_calls = value,
            ResourceDimension::Processes => next.processes = value,
            ResourceDimension::DiskBytes => next.disk_bytes = value,
            ResourceDimension::NetworkBytes => next.network_bytes = value,
            ResourceDimension::Concurrency => next.concurrency = value,
            ResourceDimension::Money => next.money_micros = value,
        }
        Ok(next)
    }

    /// Checked component-wise addition; fails closed on u64 overflow.
    pub fn checked_add(&self, other: &BudgetVector) -> Result<BudgetVector, AdmissionError> {
        let mut next = BudgetVector::ZERO;
        for dimension in ResourceDimension::ALL {
            let sum = self
                .dimension(dimension)
                .checked_add(other.dimension(dimension))
                .ok_or_else(|| {
                    AdmissionError::budget_exceeded(format!(
                        "vector addition overflows for dimension {:?}",
                        dimension
                    ))
                })?;
            next = next.with_dimension(dimension, sum)?;
        }
        Ok(next)
    }

    /// Checked component-wise subtraction; fails closed if `other` exceeds
    /// `self` in any dimension (underflow is a caller bug, not a clamp).
    pub fn checked_sub(&self, other: &BudgetVector) -> Result<BudgetVector, AdmissionError> {
        let mut next = BudgetVector::ZERO;
        for dimension in ResourceDimension::ALL {
            let diff = self
                .dimension(dimension)
                .checked_sub(other.dimension(dimension))
                .ok_or_else(|| {
                    AdmissionError::invalid_transition(format!(
                        "vector subtraction underflows for dimension {:?}",
                        dimension
                    ))
                })?;
            next = next.with_dimension(dimension, diff)?;
        }
        Ok(next)
    }

    pub fn is_zero(&self) -> bool {
        ResourceDimension::ALL
            .iter()
            .all(|dimension| self.dimension(*dimension) == 0)
    }
}

/// Per-dimension hard caps for a budget envelope.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ResourceCaps {
    pub input_tokens: CapLimit,
    pub output_tokens: CapLimit,
    pub cache_read_tokens: CapLimit,
    pub cache_write_tokens: CapLimit,
    pub wall_time_ms: CapLimit,
    pub tool_calls: CapLimit,
    pub processes: CapLimit,
    pub disk_bytes: CapLimit,
    pub network_bytes: CapLimit,
    pub concurrency: CapLimit,
    pub money: CapLimit,
}

impl ResourceCaps {
    pub fn cap(&self, dimension: ResourceDimension) -> CapLimit {
        match dimension {
            ResourceDimension::InputTokens => self.input_tokens,
            ResourceDimension::OutputTokens => self.output_tokens,
            ResourceDimension::CacheReadTokens => self.cache_read_tokens,
            ResourceDimension::CacheWriteTokens => self.cache_write_tokens,
            ResourceDimension::WallTimeMs => self.wall_time_ms,
            ResourceDimension::ToolCalls => self.tool_calls,
            ResourceDimension::Processes => self.processes,
            ResourceDimension::DiskBytes => self.disk_bytes,
            ResourceDimension::NetworkBytes => self.network_bytes,
            ResourceDimension::Concurrency => self.concurrency,
            ResourceDimension::Money => self.money,
        }
    }

    /// Atomic admission check: for every hard-capped dimension, verifies
    /// `committed + reserved + requested <= cap`. Returns the first violated
    /// (or overflowing) dimension with the projected total and the limit.
    /// Dimensions marked `NotApplicable` are skipped here; whether a skipped
    /// dimension was actually required is enforced by [`BudgetEnvelope`].
    pub fn check_admission(
        &self,
        committed: &BudgetVector,
        reserved: &BudgetVector,
        requested: &BudgetVector,
    ) -> Result<(), (ResourceDimension, u64, u64)> {
        for dimension in ResourceDimension::ALL {
            let cap = self.cap(dimension);
            let limit = match cap {
                CapLimit::NotApplicable => continue,
                CapLimit::HardCap(limit) => limit,
            };
            let projected = committed
                .dimension(dimension)
                .checked_add(reserved.dimension(dimension))
                .and_then(|value| value.checked_add(requested.dimension(dimension)));
            let projected = match projected {
                Some(value) => value,
                None => return Err((dimension, u64::MAX, limit)),
            };
            if projected > limit {
                return Err((dimension, projected, limit));
            }
        }
        Ok(())
    }
}

/// Validated integer pricing snapshot bound to one provider/model in one
/// local currency. Prices are micro currency units per million tokens.
/// The original profile snapshot hash is kept for audit; conversion from
/// the existing `f64` catalog pricing happens in `budget::pricing` with
/// deterministic round-up and never feeds `f64` into ledger counters.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct PricingSnapshot {
    pub currency_code: String,
    pub provider_id: String,
    pub model_id: String,
    pub input_micros_per_million: u64,
    pub output_micros_per_million: u64,
    pub cache_read_micros_per_million: u64,
    pub cache_write_micros_per_million: u64,
    /// `None` means reasoning tokens are priced as output tokens.
    pub reasoning_micros_per_million: Option<u64>,
    /// Multiplier in micro units: 1_000_000 == 1.0.
    pub multiplier_micros: u64,
    /// Hash of the original profile pricing payload for audit.
    pub source_hash: String,
}

impl PricingSnapshot {
    pub fn validate(&self) -> Result<(), AdmissionError> {
        if self.currency_code.trim().is_empty() {
            return Err(AdmissionError::unpriced_model(
                "pricing snapshot has an empty currency code",
            ));
        }
        if self.provider_id.trim().is_empty() || self.model_id.trim().is_empty() {
            return Err(AdmissionError::unpriced_model(
                "pricing snapshot is not bound to a provider/model",
            ));
        }
        if self.multiplier_micros == 0 {
            return Err(AdmissionError::unpriced_model(
                "pricing snapshot multiplier must be positive",
            ));
        }
        if self.source_hash.trim().is_empty() {
            return Err(AdmissionError::unpriced_model(
                "pricing snapshot is missing its source hash",
            ));
        }
        Ok(())
    }
}

/// Monetary mode of a budget envelope. The two modes are explicitly
/// distinguishable: a missing currency configuration is never interpreted
/// as "free".
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case", tag = "mode")]
pub enum MoneyMode {
    /// No monetary cap. Token/resource hard caps still apply. Suitable for
    /// free models or experiments that only compare token consumption.
    TokenResourceOnly,
    /// Monetary hard cap in a profile-declared local currency. Requires a
    /// validated pricing snapshot in the same currency.
    Money {
        currency_code: String,
        cap_money_micros: u64,
        pricing: PricingSnapshot,
    },
}

/// Frozen budget profile for a scope chain.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct BudgetEnvelope {
    pub caps: ResourceCaps,
    /// Dimensions that must be reliably observable for every admitted
    /// effect. A required dimension without a hard cap (or without a
    /// working measurement) fails admission closed.
    pub required_dimensions: BTreeSet<ResourceDimension>,
    pub money_mode: MoneyMode,
    /// Maximum number of real outbound attempts per effect. Defaults to 1;
    /// every attempt gets its own reservation.
    pub max_attempts: u32,
    /// Number of infra failures that pauses the campaign scope.
    pub infra_failure_threshold: u32,
    /// Reservation lease duration in milliseconds before recovery may
    /// reconcile an abandoned reservation.
    pub reservation_lease_ms: u64,
}

impl BudgetEnvelope {
    /// Validates envelope invariants:
    /// - money mode and money cap must be configured together;
    /// - token/resource-only mode must not carry a money cap;
    /// - every required dimension must have a hard cap;
    /// - `max_attempts` is at least 1.
    pub fn validate(&self) -> Result<(), AdmissionError> {
        match &self.money_mode {
            MoneyMode::TokenResourceOnly => {
                if self.caps.money.limit().is_some() {
                    return Err(AdmissionError::invalid_scope_chain(
                        "token/resource-only envelope must not carry a money cap",
                    ));
                }
            }
            MoneyMode::Money {
                currency_code,
                cap_money_micros,
                pricing,
            } => {
                pricing.validate()?;
                if pricing.currency_code != *currency_code {
                    return Err(AdmissionError::unpriced_model(format!(
                        "pricing snapshot currency {} does not match envelope currency {}",
                        pricing.currency_code, currency_code
                    )));
                }
                match self.caps.money {
                    CapLimit::HardCap(limit) if limit == *cap_money_micros => {}
                    _ => {
                        return Err(AdmissionError::invalid_scope_chain(
                            "money-budget envelope must carry a matching positive money hard cap",
                        ));
                    }
                }
            }
        }
        for dimension in &self.required_dimensions {
            if self.caps.cap(*dimension).limit().is_none() {
                return Err(AdmissionError::resource_unobservable(format!(
                    "required dimension {dimension:?} has no hard cap in the envelope"
                )));
            }
        }
        if self.max_attempts == 0 {
            return Err(AdmissionError::invalid_scope_chain(
                "max_attempts must be at least 1",
            ));
        }
        Ok(())
    }
}

/// The kind of physical effect being admitted.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EffectKind {
    /// Outbound LLM chat/completion request.
    LlmCompletion,
    /// Outbound embedding request.
    Embedding,
    /// Physical tool invocation.
    ToolCall,
    /// OS process spawn.
    Process,
}

/// A reservation request for one effect attempt. All identifiers are
/// backend-generated opaque strings.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReserveEffect {
    pub effect_id: String,
    pub idempotency_key: String,
    pub scopes: ScopeChain,
    pub effect_kind: EffectKind,
    /// 1-based attempt number; must not exceed the envelope `max_attempts`.
    pub attempt: u32,
    /// Worst-case estimated resource vector for this attempt.
    pub estimate: BudgetVector,
}

impl ReserveEffect {
    pub fn validate(&self) -> Result<(), AdmissionError> {
        if self.effect_id.trim().is_empty() {
            return Err(AdmissionError::invalid_scope_chain(
                "effect id must be a non-empty backend-generated identifier",
            ));
        }
        if self.idempotency_key.trim().is_empty() {
            return Err(AdmissionError::invalid_scope_chain(
                "idempotency key must be a non-empty backend-generated identifier",
            ));
        }
        if self.attempt == 0 {
            return Err(AdmissionError::invalid_scope_chain(
                "attempt numbering starts at 1",
            ));
        }
        self.scopes.validate()
    }
}

/// Durable reservation states.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReservationState {
    /// Effect admitted, budget occupied, effect not yet settled.
    Reserved,
    /// Actual usage committed (possibly equal to the estimate).
    Committed,
    /// Proven not to have produced any physical effect; budget released.
    Released,
    /// The effect may have happened but the outcome is unknown; budget
    /// stays frozen until owner reconciliation. Never treated as zero cost.
    Unknown,
    /// Actual usage exceeded the reservation; recorded and the owning
    /// campaign is paused for subsequent admissions.
    Overrun,
}

impl ReservationState {
    /// Whether a transition from `self` to `next` is legal. Terminal states
    /// (`Committed`, `Released`, `Unknown`, `Overrun`) accept no further
    /// transitions; idempotent replays of the same terminal state are
    /// handled by the store via operation IDs, not by re-transitioning.
    pub fn can_transition(&self, next: ReservationState) -> bool {
        match self {
            ReservationState::Reserved => matches!(
                next,
                ReservationState::Committed
                    | ReservationState::Released
                    | ReservationState::Unknown
                    | ReservationState::Overrun
            ),
            ReservationState::Committed
            | ReservationState::Released
            | ReservationState::Unknown
            | ReservationState::Overrun => false,
        }
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            ReservationState::Reserved => "reserved",
            ReservationState::Committed => "committed",
            ReservationState::Released => "released",
            ReservationState::Unknown => "unknown",
            ReservationState::Overrun => "overrun",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "reserved" => Some(ReservationState::Reserved),
            "committed" => Some(ReservationState::Committed),
            "released" => Some(ReservationState::Released),
            "unknown" => Some(ReservationState::Unknown),
            "overrun" => Some(ReservationState::Overrun),
            _ => None,
        }
    }
}

/// A durable reservation receipt returned by a successful reserve.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct Reservation {
    pub reservation_id: String,
    pub effect_id: String,
    pub idempotency_key: String,
    pub scopes: ScopeChain,
    pub effect_kind: EffectKind,
    pub attempt: u32,
    pub reserved: BudgetVector,
    pub state: ReservationState,
    pub created_at_ms: u64,
    pub lease_expires_at_ms: u64,
}

/// Receipt for a successful commit (reserved -> committed/overrun).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct CommitReceipt {
    pub reservation_id: String,
    pub operation_id: String,
    pub committed: BudgetVector,
    /// True when actual usage exceeded the reservation; the campaign is
    /// paused for subsequent admissions in this case.
    pub overrun: bool,
}

/// Receipt for a proven no-effect release.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct ReleaseReceipt {
    pub reservation_id: String,
    pub operation_id: String,
}

/// Receipt for marking an effect outcome unknown.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct UnknownReceipt {
    pub reservation_id: String,
    pub operation_id: String,
}

/// Receipt for an infra failure record; reports the campaign pause state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub struct InfraReceipt {
    pub campaign_id: String,
    pub infra_failure_count: u64,
    pub paused: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn chain() -> ScopeChain {
        ScopeChain {
            request_id: "req-1".into(),
            trial_id: "trial-1".into(),
            candidate_id: "cand-1".into(),
            campaign_id: "camp-1".into(),
        }
    }

    fn vector(values: &[(ResourceDimension, u64)]) -> BudgetVector {
        let mut vector = BudgetVector::ZERO;
        for (dimension, value) in values {
            vector = vector.with_dimension(*dimension, *value).unwrap();
        }
        vector
    }

    fn caps() -> ResourceCaps {
        ResourceCaps {
            input_tokens: CapLimit::HardCap(1_000),
            output_tokens: CapLimit::HardCap(1_000),
            cache_read_tokens: CapLimit::NotApplicable,
            cache_write_tokens: CapLimit::NotApplicable,
            wall_time_ms: CapLimit::HardCap(60_000),
            tool_calls: CapLimit::HardCap(10),
            processes: CapLimit::HardCap(2),
            disk_bytes: CapLimit::NotApplicable,
            network_bytes: CapLimit::NotApplicable,
            concurrency: CapLimit::HardCap(2),
            money: CapLimit::NotApplicable,
        }
    }

    fn snapshot(currency: &str) -> PricingSnapshot {
        PricingSnapshot {
            currency_code: currency.into(),
            provider_id: "prov".into(),
            model_id: "model".into(),
            input_micros_per_million: 1_000,
            output_micros_per_million: 2_000,
            cache_read_micros_per_million: 100,
            cache_write_micros_per_million: 200,
            reasoning_micros_per_million: None,
            multiplier_micros: 1_000_000,
            source_hash: "hash".into(),
        }
    }

    #[test]
    fn scope_kind_chain_is_ordered() {
        assert_eq!(ScopeKind::Request.parent(), Some(ScopeKind::Trial));
        assert_eq!(ScopeKind::Trial.parent(), Some(ScopeKind::Candidate));
        assert_eq!(ScopeKind::Candidate.parent(), Some(ScopeKind::Campaign));
        assert_eq!(ScopeKind::Campaign.parent(), None);
        assert_eq!(ScopeKind::parse("trial"), Some(ScopeKind::Trial));
        assert_eq!(ScopeKind::parse("bogus"), None);
    }

    #[test]
    fn scope_chain_rejects_empty_and_duplicate_ids() {
        assert!(chain().validate().is_ok());
        let mut empty = chain();
        empty.request_id = " ".into();
        assert!(empty.validate().is_err());
        let mut duplicate = chain();
        duplicate.trial_id = "req-1".into();
        assert!(duplicate.validate().is_err());
    }

    #[test]
    fn vector_checked_add_overflows_fail_closed() {
        // Built directly (not via with_dimension) to exercise the u64
        // addition guard independently of the SQLite range constructor.
        let large = BudgetVector {
            input_tokens: u64::MAX,
            ..BudgetVector::ZERO
        };
        let small = vector(&[(ResourceDimension::InputTokens, 1)]);
        // Any addition involving an out-of-range component fails closed
        // (the result guard rejects values beyond the SQLite range).
        assert!(large.checked_add(&small).is_err());
        assert!(large.checked_add(&BudgetVector::ZERO).is_err());
        // Exact addition of SQLite-valid vectors stays exact.
        let left = vector(&[(ResourceDimension::InputTokens, 2)]);
        let right = vector(&[(ResourceDimension::InputTokens, 3)]);
        assert_eq!(left.checked_add(&right).unwrap().input_tokens, 5);
    }

    #[test]
    fn vector_checked_sub_underflows_fail_closed() {
        let small = vector(&[(ResourceDimension::OutputTokens, 3)]);
        let large = vector(&[(ResourceDimension::OutputTokens, 5)]);
        assert!(small.checked_sub(&large).is_err());
        assert_eq!(large.checked_sub(&small).unwrap().output_tokens, 2);
    }

    #[test]
    fn admission_check_enforces_committed_plus_reserved_plus_requested() {
        let caps = caps();
        let committed = vector(&[(ResourceDimension::InputTokens, 600)]);
        let reserved = vector(&[(ResourceDimension::InputTokens, 300)]);
        // Exactly at cap succeeds.
        let exact = vector(&[(ResourceDimension::InputTokens, 100)]);
        assert!(caps.check_admission(&committed, &reserved, &exact).is_ok());
        // One unit over fails with the offending dimension.
        let over = vector(&[(ResourceDimension::InputTokens, 101)]);
        let (dimension, projected, limit) = caps
            .check_admission(&committed, &reserved, &over)
            .unwrap_err();
        assert_eq!(dimension, ResourceDimension::InputTokens);
        assert_eq!(projected, 1_001);
        assert_eq!(limit, 1_000);
    }

    #[test]
    fn not_applicable_dimensions_are_skipped_not_zero() {
        let caps = caps();
        // cache_read is NotApplicable; a huge requested value must not trip
        // the cap check here (requirement enforcement lives in the envelope
        // and the effect owner measurement contract).
        let huge = vector(&[
            (ResourceDimension::CacheReadTokens, SQLITE_INTEGER_MAX),
            (ResourceDimension::InputTokens, 1),
        ]);
        assert!(caps
            .check_admission(&BudgetVector::ZERO, &BudgetVector::ZERO, &huge)
            .is_ok());
    }

    #[test]
    fn envelope_requires_money_cap_and_pricing_together() {
        let mut envelope = BudgetEnvelope {
            caps: caps(),
            required_dimensions: BTreeSet::new(),
            money_mode: MoneyMode::TokenResourceOnly,
            max_attempts: 1,
            infra_failure_threshold: 3,
            reservation_lease_ms: 60_000,
        };
        assert!(envelope.validate().is_ok());

        // Money mode without a money cap is invalid.
        envelope.money_mode = MoneyMode::Money {
            currency_code: "cny".into(),
            cap_money_micros: 5_000_000,
            pricing: snapshot("cny"),
        };
        assert!(envelope.validate().is_err());

        // Matching money cap validates.
        envelope.caps.money = CapLimit::HardCap(5_000_000);
        assert!(envelope.validate().is_ok());

        // Currency mismatch between snapshot and envelope fails closed.
        envelope.money_mode = MoneyMode::Money {
            currency_code: "usd".into(),
            cap_money_micros: 5_000_000,
            pricing: snapshot("cny"),
        };
        assert!(envelope.validate().is_err());
    }

    #[test]
    fn token_only_mode_rejects_money_cap() {
        let mut envelope = BudgetEnvelope {
            caps: caps(),
            required_dimensions: BTreeSet::new(),
            money_mode: MoneyMode::TokenResourceOnly,
            max_attempts: 1,
            infra_failure_threshold: 3,
            reservation_lease_ms: 60_000,
        };
        envelope.caps.money = CapLimit::HardCap(1);
        assert!(envelope.validate().is_err());
    }

    #[test]
    fn required_dimensions_must_have_hard_caps() {
        let mut envelope = BudgetEnvelope {
            caps: caps(),
            required_dimensions: BTreeSet::new(),
            money_mode: MoneyMode::TokenResourceOnly,
            max_attempts: 1,
            infra_failure_threshold: 3,
            reservation_lease_ms: 60_000,
        };
        envelope
            .required_dimensions
            .insert(ResourceDimension::DiskBytes);
        // disk_bytes is NotApplicable -> required without cap fails closed.
        assert!(envelope.validate().is_err());
        envelope.caps.disk_bytes = CapLimit::HardCap(1_024);
        assert!(envelope.validate().is_ok());
    }

    #[test]
    fn max_attempts_must_be_positive() {
        let envelope = BudgetEnvelope {
            caps: caps(),
            required_dimensions: BTreeSet::new(),
            money_mode: MoneyMode::TokenResourceOnly,
            max_attempts: 0,
            infra_failure_threshold: 3,
            reservation_lease_ms: 60_000,
        };
        assert!(envelope.validate().is_err());
    }

    #[test]
    fn reservation_transitions_are_gated() {
        assert!(ReservationState::Reserved.can_transition(ReservationState::Committed));
        assert!(ReservationState::Reserved.can_transition(ReservationState::Released));
        assert!(ReservationState::Reserved.can_transition(ReservationState::Unknown));
        assert!(ReservationState::Reserved.can_transition(ReservationState::Overrun));
        // Terminal states accept nothing.
        assert!(!ReservationState::Committed.can_transition(ReservationState::Released));
        assert!(!ReservationState::Released.can_transition(ReservationState::Committed));
        assert!(!ReservationState::Unknown.can_transition(ReservationState::Released));
        assert!(!ReservationState::Overrun.can_transition(ReservationState::Committed));
        // Round-trip serialization.
        assert_eq!(
            ReservationState::parse(ReservationState::Unknown.as_str()),
            Some(ReservationState::Unknown)
        );
    }

    #[test]
    fn reserve_effect_validation_fails_closed() {
        let mut effect = ReserveEffect {
            effect_id: "eff-1".into(),
            idempotency_key: "idem-1".into(),
            scopes: chain(),
            effect_kind: EffectKind::LlmCompletion,
            attempt: 1,
            estimate: BudgetVector::ZERO,
        };
        assert!(effect.validate().is_ok());
        effect.attempt = 0;
        assert!(effect.validate().is_err());
        effect.attempt = 1;
        effect.idempotency_key = String::new();
        assert!(effect.validate().is_err());
    }

    #[test]
    fn sqlite_range_guard_rejects_overflow() {
        assert_eq!(ensure_sqlite_range(0).unwrap(), 0);
        assert_eq!(ensure_sqlite_range(SQLITE_INTEGER_MAX).unwrap(), i64::MAX);
        assert!(ensure_sqlite_range(SQLITE_INTEGER_MAX + 1).is_err());
    }

    #[test]
    fn negative_usage_is_rejected() {
        assert!(checked_usage_u64(-1, ResourceDimension::ToolCalls).is_err());
        assert_eq!(
            checked_usage_u64(7, ResourceDimension::ToolCalls).unwrap(),
            7
        );
    }

    #[test]
    fn pricing_snapshot_validation() {
        assert!(snapshot("cny").validate().is_ok());
        let mut invalid = snapshot("cny");
        invalid.currency_code = String::new();
        assert!(invalid.validate().is_err());
        let mut zero_multiplier = snapshot("cny");
        zero_multiplier.multiplier_micros = 0;
        assert!(zero_multiplier.validate().is_err());
    }
}
