use serde_json::Value;
use url::form_urlencoded::{byte_serialize, parse};

/// Formats a JSON string
///
/// JSON strings generated by AI are not always reliable and valid. The main issue is that they are often wrapped in ```json and ```,
/// which is actually Markdown format. These wrappers need to be removed, otherwise the string cannot be parsed as valid JSON. Another common issue is
/// the inclusion of newlines, which also makes the string invalid.
///
/// # Arguments
/// * `jstr` - JSON string to format
///
/// # Returns
/// The formatted JSON string
pub fn format_json_str(jstr: &str) -> String {
    let mut jstr = jstr.trim();

    // 1. Try to extract content between the first { and the last } or [ and ]
    let start_brace = jstr.find('{');
    let start_bracket = jstr.find('[');
    let end_brace = jstr.rfind('}');
    let end_bracket = jstr.rfind(']');

    let start = match (start_brace, start_bracket) {
        (Some(s1), Some(s2)) => Some(s1.min(s2)),
        (Some(s), None) | (None, Some(s)) => Some(s),
        (None, None) => None,
    };

    let end = match (end_brace, end_bracket) {
        (Some(e1), Some(e2)) => Some(e1.max(e2)),
        (Some(e), None) | (None, Some(e)) => Some(e),
        (None, None) => None,
    };

    if let (Some(s), Some(e)) = (start, end) {
        if s <= e {
            jstr = &jstr[s..=e];
        }
    }

    // Still perform some basic cleaning for malformed AI output,
    // but try to be less destructive to valid multi-line content if possible.
    // However, for tool calling, AI usually produces compact JSON or JSON with newlines for formatting.
    // If the JSON is already valid, serde_json handles it fine.
    // The previous aggressive replace('\n', "") was likely to fix raw newlines in strings.
    
    let formatted = jstr
        .trim_start_matches("```json")
        .trim_start_matches(|c: char| c == '`' || c.is_whitespace())
        .trim_end_matches(|c: char| c == '`' || c.is_whitespace())
        .trim()
        .to_string();

    // If it starts with { and ends with }, but serde_json fails, we might still need to clean it.
    // Let's keep a balance.
    formatted
}

/// URL encode a string
///
/// # Arguments
/// * `s` - The string to encode
///
/// # Returns
/// * `String` - The encoded string
pub fn urlencode(s: &str) -> String {
    byte_serialize(s.as_bytes()).collect::<String>()
}

/// URL encode a JSON value
///
/// # Arguments
/// * `s` - The JSON value to encode
///
/// # Returns
/// * `String` - The encoded string
pub fn urlencodes(s: &Value) -> String {
    match s {
        Value::String(s) => urlencode(s),
        Value::Number(n) => n.to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Array(arr) => arr.iter().map(urlencodes).collect::<Vec<_>>().join(","),
        Value::Object(obj) => obj
            .iter()
            .map(|(k, v)| format!("{}={}", urlencode(k), urlencodes(v)))
            .collect::<Vec<_>>()
            .join("&"),
        Value::Null => "".to_string(),
    }
}

/// URL decode a string
///
/// # Arguments
/// * `s` - The string to decode
///
/// # Returns
/// * `Result<String, String>` - The decoded string or error
pub fn urldecode(s: &str) -> Result<String, String> {
    let decoded: String = parse(s.as_bytes())
        .map(|(key, value)| [key, value].concat())
        .collect();

    if decoded.is_empty() && !s.is_empty() {
        Err("Failed to decode URL".to_string())
    } else {
        Ok(decoded)
    }
}
