[target.'cfg(target_os = "windows")']
rustflags = ["-C", "target-feature=+crt-static"]
VCINSTALLDIR = ""
WindowsSdkDir = ""
WindowsSDKVersion = ""
VCToolsInstallDir = ""
VCToolsVersion = ""
PreferredToolArchitecture = "x64"

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]
