[build]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# 让 build.rs 来设置这些变量
VCINSTALLDIR              = { value = "", relative = false }
WindowsSdkDir             = { value = "", relative = false }
WindowsSDKVersion         = { value = "", relative = false }
VCToolsInstallDir         = { value = "", relative = false }
VCToolsVersion            = { value = "", relative = false }
PreferredToolArchitecture = { value = "x64", relative = false }
