[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[env]
CC = { value = "cl.exe", relative = true }
CXX = { value = "cl.exe", relative = true }
